---
- name: update web, nfs and db servers
  hosts: webservers, nfs, db
  become: yes
  tasks:
    - name: ensure wireshark is at the latest version
      yum:
        name: wireshark
        state: latest
   

- name: update LB server
  hosts: lb
  become: yes
  tasks:
    - name: Update apt repo
      apt: 
        update_cache: yes

    - name: ensure wireshark is at the latest version
      apt:
        name: wireshark
        state: latest

- name: Create Directory and file
  hosts: webservers, lb, db, nfs
  become: yes
  tasks:
    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: /home/ubuntu/ansible_dir
        state: directory
        mode: '0755'

    - name: Touch a file
      ansible.builtin.file:
        path: /home/ubuntu/ansible_dir/ansible_file
        state: touch

- name: Change Timezone in Server
  hosts: all
  become: yes
  tasks:
    - name: set timezone to Africa/Lagos
      timezone:
        name: Africa/Lagos

- name: change file to executable
  hosts: all
  become: yes
  tasks:
    - name: change file to executable
      ansible.builtin.file:
        path: ./
        state: file
        mode: a+x

- name: Run a script and execute
  hosts: all
  become: yes
  tasks:
    - name: Execute the command in remote shell; stdout goes to the specified file on the remote
      ansible.builtin.shell: script.sh
      args:
        chdir: ./
        executable: /bin/bash

